# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            'Rishabh Ranawat'
tagline:          'Software Engineer @ Google'
description:      'Notes and projects.'
baseurl:          ''

author:
  name:           'Rishabh Ranawat'
  url:            https://twitter.com/rishabhranawat

paginate:         3

# Custom vars
version:          2.1.0


gems: [jekyll-gist]